### ISSUE TITLE
problems on raspberry pi (with linux)

### ISSUE THREAD

**Issue by flok99** [fluxroot/pulse#54]
Hi,

I had an issue with it not linking (using gcc (g++) 4.9.2-10). That was solved by adding apropriate -pthread here and there (see pull request).
Other problem is that it won't start at all:

root@platform-one:/usr/src/pulse# gdb /usr/local/./pulse-1.6.1-cpp  
GNU gdb (GDB) 7.4.1-debian
...
Reading symbols from /usr/local/pulse-1.6.1-cpp...done.
(gdb) r
Starting program: /usr/local/pulse-1.6.1-cpp 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0xb6f342d0 (LWP 19778)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb6f342d0 (LWP 19778)]
0x00065c44 in execute_native_thread_routine ()
(gdb) bt
#0  0x00065c44 in execute_native_thread_routine ()
#1  0x0008385c in start_thread ()
#2  0x000b5338 in ?? ()
#3  0x000b5338 in ?? ()

Backtrace stopped: previous frame identical to this frame (corrupt stack?)

The main thread seems to be running though:
Thread 1 (Thread 0x135000 (LWP 19775)):
#0  0x00085ed0 in read () at ../sysdeps/unix/syscall-template.S:81
#1  0x0009cbf8 in _IO_new_file_underflow ()
#2  0x0009f19c in _IO_default_uflow ()
#3  0x0009f030 in __uflow ()
#4  0x0009b7f0 in getc ()
#5  0x000450c8 in __gnu_cxx::stdio_sync_filebuf<char, std::char_traits<char> >::underflow() ()
#6  0x00027438 in std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char) ()
#7  0x0001a054 in pulse::Pulse::run() () at /usr/include/c++/4.9/bits/basic_string.h:2814
#8  0x00011984 in main () at /usr/src/pulse/src/main/cpp/main.cpp:24

**Comment by fluxroot** [comment]
Hey Folkert! Thanks for reporting. I'll have a look at this issue as soon as possible.

**Comment by fluxroot** [comment]
This could be an issue with static compilation. I removed the "-static" compilation flag as it is not really necessary.
