### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by MarsVard** [fluxroot/pulse#55]
Hello

Are there any examples available for this library? like checking if a move is valid or basic setup..

**Comment by fluxroot** [comment]
Hi @MarsVard. Thanks for asking. I don't fully understand your use case. Do you want to use Pulse as a library in your own Java program?
If you just want to get legal moves/check moves, JCPI (https://github.com/fluxroot/jcpi) would maybe be a better way to do it. Maybe if you explain how you would use Pulse, I could probably give a better answer.
Cheers, Poke.

**Comment by fluxroot** [comment]
I guess, this issue has been answered for you. I'll close it for now. Feel free to reopen it, if you have more questions.

**Comment by MarsVard** [comment]
Hey Fluxroot, Sorry for the late reply, I was too busy and totally forgot.

This did answered my question, I was confused, I was looking to check legal moves so I'll try JCPI.
