### ISSUE TITLE
Always loses on time

### ISSUE THREAD

**Issue by CMCanavessi** [fluxroot/pulse#67]
I was testing 1.7.1 and it will always lose on time. This didn't happen with 1.6.1 which worked just fine. 
I am using a 1 minute + 1 second time control with Arena.

**Comment by fluxroot** [comment]
Hi @CMCanavessi 
Thanks for reporting this issue. Indeed I changed the time management in version 1.7.0. I think I know where to fix this one. I'll update this issue when I have a fix ready.

**Comment by bvongunten** [comment]
Same happening on 40 moves in 5 minutes ... loosing on move 39 due to time out.

**Comment by fluxroot** [comment]
Fixed in 9c71904.
