### ISSUE TITLE
Pulse crashes when opponent's time is exactly 0

### ISSUE THREAD

**Issue by olithink** [fluxroot/pulse#84]
Hello, this is a really nice engine,
Unfortunately it has a little bug, which happen's regularly against opponent's that ca  run out of time and is easy to reproduce:
```
./pulse
go wtime 100 btime 0
terminate called after throwing an instance of 'std::exception'
  what():  std::exception
Aborted
```
This is the code in search.cpp on line 199 and 201:
```
if (whiteTimeLeft < 1) throw std::exception();
if (blackTimeLeft < 1) throw std::exception();

```
I think, those lines are not necessary and can be removed entirely (or the condition < 0). 
Then Pulse would be very stable.

Best Regards,
Oliver

**Comment by fluxroot** [comment]
@olithink Thanks for reporting this crash. Lately, I've been working on Pulse again. So I took my time to fix this one. I thought about not to throw exceptions on invalid parameters but return an error message instead. However, I guess this idea has to wait until 2.0. For version 1.7.x this fix is good enough. Cheers!
