### ISSUE TITLE
compiling gives v2.0.0 ?

### ISSUE THREAD

**Issue by tissatussa** [fluxroot/pulse#85]
i copied your newest source code (by git clone) and compiled it (on Linux) .. this gave me a proper binary but the `uci` command shows v2.0.0 !?  I expect v1.7.3 (indeed, your asset file has this version).

**Comment by fluxroot** [comment]
Hey @tissatussa 

By using `git clone` you have probably checked out the default master branch which is the next major version 2.0.0. If you want to build the latest stable version 1.7.3, check out branch 1.7.x or git tag 1.7.3. (Maybe you have to do a `git fetch` first, as I have just created branches for all minor versions) I hope, this clears things up!

Cheers,
Poke

**Comment by tissatussa** [comment]
Using 'clone' and 'fetch' is not clear to me .. to compile GitHub open source codes i learned to click the green 'Code' button, and i get an URL like your https://github.com/fluxroot/pulse.git .. then in (Linux) terminal i do "git clone [that URL] --recursive" and then follow the make / build instructions in the README .. switching from 'master' (or 'main') to another branch does not give me another URL to clone when clicking the 'Code' button .. does your 'fetch' come into play here ? Please help, i have no clue ..

**Comment by fluxroot** [comment]
No worries. To get the sources for `1.7.x` execute the following commands in your favorite shell:
```
git clone https://github.com/fluxroot/pulse.git
cd pulse
git checkout 1.7.x
```
Then build `pulse` by following the instructions in the readme.

**Comment by tissatussa** [comment]
wow !!  it worked .. i never did something like this :

```
$ git checkout 1.7.x
Branch '1.7.x' set up to track remote branch '1.7.x' from 'origin'.
Switched to a new branch '1.7.x'
```

after compiling i found the binary in [..]/build/src/main/cpp/ 
thanks !

what about `git fetch` ?  Could you elaborate on that ?

**Comment by fluxroot** [comment]
I'd better point you to a nice starting point about git: https://docs.github.com/en/get-started/using-git/about-git. Thanks!
